# Generated by Django 5.2.10 on 2026-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(db_index=True, max_length=500)),
                ('location', models.CharField(default='Remote', max_length=500)),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('posted_at', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('seniority', models.CharField(default='Not Specified', max_length=50)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-posted_at', 'title'], name='jobs_job_posted__0c9385_idx')],
            },
        ),
    ]
