# Generated by Django 5.2.10 on 2026-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        # NOTE: 'skills' and 'seniority' are deliberately NOT added here —
        # migrations 0003 and 0004 add them. This file was regenerated after
        # they existed, which duplicated the AddField ops and broke fresh
        # installs ("column skills already exists").
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Remote', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
