# Generated by Django 5.2.15 on 2026-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_company_alter_job_location_alter_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-posted_at', 'title'], name='jobs_job_posted__0c9385_idx'),
        ),
    ]
