# Generated by Django 5.2.15 on 2026-07-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_company_alter_job_posted_at_and_more'),
        ('jobs', '0006_job_enrichment_fields'),
    ]

    operations = [
    ]
