# Generated by Django 5.2.10 on 2026-02-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apirequestlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='core_apireq_user_id_5fb2d3_idx',
            old_name='core_apireq_user_id_90d95c_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='core_apireq_plan_ty_e19f69_idx',
            old_name='core_apireq_plan_ty_eb77c9_idx',
        ),
    ]
